--
-- PostgreSQL database dump
--

\restrict XQUdKaukjVM9wmW1NoExKZvEiRYqKFb1Dgy8WqxbDqVBcpeqRjYpLr7gUuz0dFK

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: miembros_proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.miembros_proyecto (
    id_miembro_proyecto bigint NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_ingreso timestamp(6) without time zone NOT NULL,
    fecha_salida timestamp(6) without time zone,
    id_proyecto bigint NOT NULL,
    id_usuario bigint NOT NULL,
    rol character varying(50) NOT NULL
);


ALTER TABLE public.miembros_proyecto OWNER TO postgres;

--
-- Name: miembros_proyecto_id_miembro_proyecto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.miembros_proyecto ALTER COLUMN id_miembro_proyecto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.miembros_proyecto_id_miembro_proyecto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyectos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyectos (
    id_proyecto bigint NOT NULL,
    categoria character varying(100),
    codigo_proyecto character varying(50) NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    descripcion text,
    estado_proyecto character varying(50) NOT NULL,
    fecha_finalizacion date,
    fecha_inicio date,
    icono_proyecto character varying(100),
    id_usuario_creador bigint NOT NULL,
    nombre_proyecto character varying(200) NOT NULL,
    update_at timestamp(6) without time zone
);


ALTER TABLE public.proyectos OWNER TO postgres;

--
-- Name: proyectos_id_proyecto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proyectos ALTER COLUMN id_proyecto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_id_proyecto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id_usuario bigint NOT NULL,
    apellidos character varying(100) NOT NULL,
    cargo character varying(100),
    correo character varying(150) NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    empresa character varying(150),
    estado character varying(20) NOT NULL,
    foto character varying(500),
    nombre character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    telefono character varying(20),
    update_at timestamp(6) without time zone
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: miembros_proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.miembros_proyecto (id_miembro_proyecto, estado, fecha_ingreso, fecha_salida, id_proyecto, id_usuario, rol) FROM stdin;
1	activo	2026-01-11 19:37:49.336151	\N	2	4	OWNER
2	activo	2026-01-11 19:40:13.786867	\N	2	3	ADMIN
\.


--
-- Data for Name: proyectos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyectos (id_proyecto, categoria, codigo_proyecto, create_at, descripcion, estado_proyecto, fecha_finalizacion, fecha_inicio, icono_proyecto, id_usuario_creador, nombre_proyecto, update_at) FROM stdin;
1	Desarrollo	ATA-1	2026-01-08 18:52:35.315379	Proyecto de ejemplo	PLANIFICACION	\N	2026-01-10	\N	3	App de Gestión	2026-01-08 18:52:35.315379
2	Desarrollo	ATA-3	2026-01-11 19:35:43.508268	Mi primer proyecto	PLANIFICACION	\N	2026-01-10	\N	4	App de Gestión	2026-01-11 19:35:43.508268
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id_usuario, apellidos, cargo, correo, create_at, empresa, estado, foto, nombre, password, telefono, update_at) FROM stdin;
2	Pérez García	CEO	juan@mail.com	2026-01-08 03:13:00.128745	LVL Consulting	inactivo	https://ejemplo.com/foto.jpg	Juan Carlos	12345	987654321	2026-01-08 17:29:54.772298
3	Haro Francisco	\N	tomasHF@gmail.com	2026-01-08 18:51:24.340928	\N	activo	\N	Tomas	12345	\N	2026-01-08 18:51:24.342048
4	Rojas	\N	pedro@gmail.com	2026-01-11 19:33:57.332998	\N	activo	\N	Pedro	12345	\N	2026-01-11 19:33:57.332998
\.


--
-- Name: miembros_proyecto_id_miembro_proyecto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.miembros_proyecto_id_miembro_proyecto_seq', 2, true);


--
-- Name: proyectos_id_proyecto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proyectos_id_proyecto_seq', 2, true);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 4, true);


--
-- Name: miembros_proyecto miembros_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.miembros_proyecto
    ADD CONSTRAINT miembros_proyecto_pkey PRIMARY KEY (id_miembro_proyecto);


--
-- Name: proyectos proyectos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT proyectos_pkey PRIMARY KEY (id_proyecto);


--
-- Name: proyectos uk3voy0wtyoobudirwlycydshhh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT uk3voy0wtyoobudirwlycydshhh UNIQUE (codigo_proyecto);


--
-- Name: usuarios ukcdmw5hxlfj78uf4997i3qyyw5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- PostgreSQL database dump complete
--

\unrestrict XQUdKaukjVM9wmW1NoExKZvEiRYqKFb1Dgy8WqxbDqVBcpeqRjYpLr7gUuz0dFK

