-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.miembros_proyecto
(
    id_miembro_proyecto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_ingreso timestamp(6) without time zone NOT NULL,
    fecha_salida timestamp(6) without time zone,
    id_proyecto bigint NOT NULL,
    id_usuario bigint NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT miembros_proyecto_pkey PRIMARY KEY (id_miembro_proyecto)
);

CREATE TABLE IF NOT EXISTS public.proyectos
(
    id_proyecto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    categoria character varying(100) COLLATE pg_catalog."default",
    codigo_proyecto character varying(50) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado_proyecto character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_finalizacion date,
    fecha_inicio date,
    icono_proyecto character varying(100) COLLATE pg_catalog."default",
    id_usuario_creador bigint NOT NULL,
    nombre_proyecto character varying(200) COLLATE pg_catalog."default" NOT NULL,
    update_at timestamp(6) without time zone,
    CONSTRAINT proyectos_pkey PRIMARY KEY (id_proyecto),
    CONSTRAINT uk3voy0wtyoobudirwlycydshhh UNIQUE (codigo_proyecto)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cargo character varying(100) COLLATE pg_catalog."default",
    correo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    empresa character varying(150) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    foto character varying(500) COLLATE pg_catalog."default",
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    update_at timestamp(6) without time zone,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo)
);

ALTER TABLE IF EXISTS public.proyectos
    ADD FOREIGN KEY (id_proyecto)
    REFERENCES public.miembros_proyecto (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios
    ADD FOREIGN KEY (id_usuario)
    REFERENCES public.proyectos (id_usuario_creador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios
    ADD FOREIGN KEY (id_usuario)
    REFERENCES public.miembros_proyecto (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;